---
name: Apache-SPARQL-RDFStore
version: 0.3
author:
  - Alberto Reggiori <alberto@asemantics.com>
abstract: A mod_perl handler which implements SPARQL bindings with RDFStore
license: bsd
requires:
  Apache::Request: >= 1.3
  Apache::SPARQL: >= 0.22
  DBI: >= 1.00
  LWP::UserAgent: >  1.00
  RDFStore: >= 0.51
  XML::LibXML: >= 1.58
  XML::LibXSLT: >= 1.52
  mod_perl: >= 1.29
provides:
  Apache::SPARQL::RDFStore:
    file: lib/Apache/SPARQL/RDFStore.pm
    version: 0.3
generated_by: Module::Build version 0.2608
